# Generated by Django 3.2.20 on 2023-08-06 00:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('track_routine', '0001_initial'),
        ('daily_commitments', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='PersonalTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('duration', models.IntegerField(blank=True, null=True)),
                ('order', models.PositiveIntegerField(default=1)),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='TrackedTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('completed', models.BooleanField(default=False)),
                ('personal_routine', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='personal_routine', to='track_routine.routinetasks', verbose_name='personal_routine')),
                ('personal_task', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_task', to='tasks.personaltasks', verbose_name='personal_task')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Tasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('task', models.CharField(max_length=50)),
                ('task_type', models.CharField(choices=[('Evening', 'Evening'), ('Morning', 'Morning')], max_length=9)),
                ('custom', models.BooleanField(default=False)),
                ('health_area', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='task_health_area', to='daily_commitments.userhealtharea', verbose_name='health_area')),
                ('users', models.ManyToManyField(related_name='users_ptasks', through='tasks.PersonalTasks', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='personaltasks',
            name='task_id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='task_id', to='tasks.tasks', verbose_name='task_id'),
        ),
        migrations.AddField(
            model_name='personaltasks',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
