# Generated by Django 3.2.20 on 2023-08-07 19:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserHealthArea',
            fields=[
                ('health_area', models.CharField(choices=[('Relieve Stress or Anxiety', 'Relieve Stress or Anxiety'), ('Improve Self-Awareness', 'Improve Self-Awareness'), ('Have a Balanced Lifestyle', 'Have a Balanced Lifestyle'), ('Reduce Anger', 'Reduce Anger'), ('None', 'None')], default='None', max_length=30, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='UserTimeCommitments',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='commitments', serialize=False, to='auth.user', verbose_name='user')),
                ('hours_of_sleep', models.IntegerField(blank=True, null=True)),
                ('work_time_from', models.TimeField(blank=True, null=True)),
                ('work_time_to', models.TimeField(blank=True, null=True)),
                ('commute_time', models.IntegerField(blank=True, null=True)),
                ('get_ready_time', models.IntegerField(blank=True, default=0, null=True)),
                ('wake_time', models.TimeField(blank=True, null=True)),
            ],
        ),
    ]
