# Generated by Django 3.2.20 on 2024-06-18 14:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom_login', '0001_initial'),
        ('daily_commitments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='health_area',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='user_health_area', to='daily_commitments.userhealtharea', verbose_name='user_health_area'),
        ),
    ]
