# Generated by Django 3.2.20 on 2024-06-18 14:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('custom_login', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='RoutineTasks',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day', models.DateField(auto_now=True, verbose_name='routine_day')),
                ('routine_type', models.CharField(choices=[('Evening', 'Evening'), ('Morning', 'Morning')], max_length=9)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_routine_fid', to='custom_login.userprofile', verbose_name='user')),
            ],
        ),
    ]
